### ISSUE TITLE
有没有大佬写一个控制台进行对话的，我微信进不去

### ISSUE THREAD

**Issue by dongandi** [wangle1218/KBQA-for-Diagnosis#19]

**Comment by hyace** [comment]
微信接口应该是被封了，自己改一个啊，也太简单了，动不了20行代码

**Comment by yangyangD-hub** [comment]
> 微信接口应该是被封了，自己改一个啊，也太简单了，动不了20行代码

那大佬写一个吧 蹲一下 谢谢

**Comment by geoluan95** [comment]
可以使用itchat-uos, pip install itchat-uos后就可以使用itchat了。

**Comment by hjing100** [comment]
> 

我改为itchat-uos后报错：
Traceback (most recent call last):
  File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 21, in dump_login_status
    with open(fileDir, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './logs/loginInfo.pkl'

**Comment by coilroll** [comment]
大佬们解决了吗？这里蹲一个

**Comment by xiefangzhenz** [comment]
> > 
> 
> 我改为itchat-uos后报错： Traceback (most recent call last): File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 21, in dump_login_status with open(fileDir, 'w') as f: FileNotFoundError: [Errno 2] No such file or directory: './logs/loginInfo.pkl'

把这个文件路径改了就行了

**Comment by jackjieliu** [comment]
> > > 
> > 
> > 
> > 我改为itchat-uos后报错： Traceback (most recent call last): File "D:\software\Anaconda36\Anacondasoftware36\lib\site-packages\itchat\components\hotreload.py", line 21, in dump_login_status with open(fileDir, 'w') as f: FileNotFoundError: [Errno 2] No such file or directory: './logs/loginInfo.pkl'
> 
> 把这个文件路径改了就行了
这个./logs/loginInfo.pkl文件找不到啊，还是说要自己生成

**Comment by alexcd90** [comment]
用input+while循环调用text_replay方法就行

**Comment by ganzii** [comment]
> 

你好请问具体实现的代码吗
