### ISSUE TITLE
报错keyerror wxsid

### ISSUE THREAD

**Issue by baobaotql** [wangle1218/KBQA-for-Diagnosis#25]
Traceback (most recent call last):
  File "itchat_app.py", line 59, in <module>
    itchat.auto_login(hotReload=True, enableCmdQR=2, statusStorageDir='D:/GitHubDesktop/KBQA-for-Diagnosis/logs/loginInfo.pkl')
  File "D:\anaconda3\lib\site-packages\itchat\components\register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\anaconda3\lib\site-packages\itchat\components\login.py", line 55, in login
    status = self.check_login()
  File "D:\anaconda3\lib\site-packages\itchat\components\login.py", line 141, in check_login
    if process_login_info(self, r.text):
  File "D:\anaconda3\lib\site-packages\itchat\components\login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]

有没有兄弟遇到这个问题 解决了么？

**Comment by coilroll** [comment]
我也遇到了，好像是现在微信登录已经用不了了，请问您现在解决了吗？
