### ISSUE TITLE
运行bulid_kg_utils.py时出现以下错误：

### ISSUE THREAD

**Issue by tandao6** [wangle1218/KBQA-for-Diagnosis#30]
写入 疾病 实体的属性
 22%|████████▋                              | 1765/7916 [01:48<06:42, 15.27it/s][Statement.SyntaxError] Unexpected end of input: expected whitespace or an expression (line 3, column 40 (offset: 96))

MATCH (n:疾病)
                        WHERE n.name='肺纤维化'

报这个错，有伙伴帮忙看下吗？是什么问题？

**Comment by Love-percation** [comment]
> 写入 疾病 实体的属性 22%|████████▋ | 1765/7916 [01:48<06:42, 15.27it/s][Statement.SyntaxError] Unexpected end of input: expected whitespace or an expression (line 3, column 40 (offset: 96))
> 
> MATCH (n:疾病) WHERE n.name='肺纤维化'
> 
> 报这个错，有伙伴帮忙看下吗？是什么问题？

大佬，请问你解决了这个问题没呀，我也报了这个错误

**Comment by Mr1meng** [comment]
我也出现这个问题了，请有解决的吗

**Comment by niumermrer** [comment]
+1同问题，不知道怎么解决，但是看后面好像又写入了

写入 疾病 实体的属性
  0%|                                                  | 0/7916 [00:00<?, ?it/s]Traceback (most recent call last):
  File "build_kg_utils.py", line 328, in <module>
    extractor.export_entitys_relations()
  File "build_kg_utils.py", line 299, in export_entitys_relations
    self.export_data(self.recipes,'./graph_data/recipes.json')
  File "build_kg_utils.py", line 292, in export_data
    if isinstance(data[0],str):
IndexError: list index out of range
 22%|████████▋                              | 1766/7916 [03:15<12:54,  7.94it/s][Statement.SyntaxError] Unexpected end of input: expected whitespace or an expression (line 3, column 40 (offset: 96))
"                        set n.cure_way="
                                        ^
MATCH (n:疾病)
                        WHERE n.name='肺纤维化'

100%|███████████████████████████████████████| 7916/7916 [18:52<00:00,  6.99it/s]

**Comment by chang126** [comment]
你们咋获取的medical.json啊，那个github里不开放下载啊

**Comment by RickoNoNo3** [comment]
同样的问题，检查代码发现tqdm每一步都包裹在try-except里，所以这个肺纤维化的问题只影响一条数据，别的数据都正常，实测也看不出来影响使用

@chang126 https://github.com/liuhuanyong/QASystemOnMedicalKG/blob/master/data/medical.json
